apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
  namespace: hireverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: hireverse/chat-server
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET_KEY
          envFrom:
            - configMapRef:
                name: common-config

---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
  namespace: hireverse
spec:
  selector:
    app: chat
  ports:
    - name: express
      protocol: TCP
      port: 5006
      targetPort: 5006
    - name: grpc
      protocol: TCP
      port: 6006
      targetPort: 6006
    - name: websocket
      protocol: TCP
      port: 7006
      targetPort: 7006